#include<iostream.h>
#include<conio.h>
#include<string.h>
#include<dos.h>
#include<process.h>
#include<graphics.h>
#include<stdlib.h>
void main()
{
    int gd=DETECT,gm;
    initgraph(&gd,&gm,"c:\\turboc3\\bgi");
    setbkcolor(WHITE);
    int Y=150,X=100,i=0,z=4;
// LINE 0
    for(i=39; i<54; i++)
    {
        putpixel(X+i,Y+0,z);
    }
// LINE 1
    for(i=34; i<60; i++)
    {
        putpixel(X+i,Y+1,z);
    }
// LINE 2
    for(i=31; i<62; i++)
    {
        putpixel(X+i,Y+2,z);
    }
// LINE 3
    for(i=28; i<64; i++)
    {
        putpixel(X+i,Y+3,z);
    }
// LINE 4
    for(i=26; i<66; i++)
    {
        putpixel(X+i,Y+4,z);
    }
// LINE 5
    for(i=25; i<70; i++)
    {
        putpixel(X+i,Y+5,z);
    }
// LINE 6
    for(i=23; i<46; i++)
    {
        putpixel(X+i,Y+6,z);
    }
    for(i=49; i<75; i++)
    {
        putpixel(X+i,Y+6,z);
    }
// LINE 7
    for(i=22; i<46; i++)
    {
        putpixel(X+i,Y+7,z);
    }
    for(i=48; i<78; i++)
    {
        putpixel(X+i,Y+7,z);
    }
// LINE 8
    for(i=21; i<45; i++)
    {
        putpixel(X+i,Y+8,z);
    }
    for(i=49; i<80; i++)
    {
        putpixel(X+i,Y+8,z);
    }
// LINE 9
    for(i=20; i<48; i++)
    {
        putpixel(X+i,Y+9,z);
    }
    for(i=50; i<82; i++)
    {
        putpixel(X+i,Y+9,z);
    }
// LINE 10
    for(i=20; i<83; i++)
    {
        putpixel(X+i,Y+10,z);
    }
// LINE 11
    for(i=19; i<84; i++)
    {
        putpixel(X+i,Y+11,z);
    }
// LINE 12
    for(i=18; i<85; i++)
    {
        putpixel(X+i,Y+12,z);
    }
// LINE 13
    for(i=18; i<86; i++)
    {
        putpixel(X+i,Y+13,z);
    }
// LINE 14
    for(i=18; i<87; i++)
    {
        putpixel(X+i,Y+14,z);
    }
// LINE 15
    for(i=18; i<88; i++)
    {
        putpixel(X+i,Y+15,z);
    }
// LINE 16
    for(i=18; i<88; i++)
    {
        putpixel(X+i,Y+16,z);
    }
// LINE 17
    for(i=17; i<40; i++)
    {
        putpixel(X+i,Y+17,z);
    }
    for(i=49; i<89; i++)
    {
        putpixel(X+i,Y+17,z);
    }
// LINE 18
    for(i=17; i<35; i++)
    {
        putpixel(X+i,Y+18,z);
    }
    for(i=57; i<90; i++)
    {
        putpixel(X+i,Y+18,z);
    }
// LINE 19
    for(i=16; i<31; i++)
    {
        putpixel(X+i,Y+19,z);
    }
    for(i=62; i<91; i++)
    {
        putpixel(X+i,Y+19,z);
    }
// LINE 20
    for(i=16; i<29; i++)
    {
        putpixel(X+i,Y+20,z);
    }
    for(i=65; i<92; i++)
    {
        putpixel(X+i,Y+20,z);
    }
// LINE 21
    for(i=15; i<28; i++)
    {
        putpixel(X+i,Y+21,z);
    }
    for(i=68; i<93; i++)
    {
        putpixel(X+i,Y+21,z);
    }
// LINE 22
    for(i=15; i<27; i++)
    {
        putpixel(X+i,Y+22,z);
    }
    for(i=70; i<93; i++)
    {
        putpixel(X+i,Y+22,z);
    }
// LINE 23
    for(i=16; i<26; i++)
    {
        putpixel(X+i,Y+23,z);
    }
    for(i=72; i<94; i++)
    {
        putpixel(X+i,Y+23,z);
    }
// LINE 24
    for(i=16; i<25; i++)
    {
        putpixel(X+i,Y+24,z);
    }
    for(i=74; i<94; i++)
    {
        putpixel(X+i,Y+24,z);
    }
// LINE 25
    for(i=17; i<25; i++)
    {
        putpixel(X+i,Y+25,z);
    }
    for(i=74; i<94; i++)
    {
        putpixel(X+i,Y+25,z);
    }
// LINE 26
    for(i=18; i<26; i++)
    {
        putpixel(X+i,Y+26,z);
    }
    for(i=75; i<94; i++)
    {
        putpixel(X+i,Y+26,z);
    }
// LINE 27
    for(i=18; i<26; i++)
    {
        putpixel(X+i,Y+27,z);
    }
    for(i=66; i<70; i++)
    {
        putpixel(X+i,Y+27,z);
    }
    for(i=75; i<95; i++)
    {
        putpixel(X+i,Y+27,z);
    }
// LINE 28
    for(i=17; i<26; i++)
    {
        putpixel(X+i,Y+28,z);
    }
    for(i=30; i<34; i++)
    {
        putpixel(X+i,Y+28,z);
    }
    for(i=54; i<71; i++)
    {
        putpixel(X+i,Y+28,z);
    }
    for(i=75; i<95; i++)
    {
        putpixel(X+i,Y+28,z);
    }
// LINE 29
    for(i=16; i<25; i++)
    {
        putpixel(X+i,Y+29,z);
    }
    for(i=28; i<45; i++)
    {
        putpixel(X+i,Y+29,z);
    }
    for(i=53; i<73; i++)
    {
        putpixel(X+i,Y+29,z);
    }
    for(i=76; i<95; i++)
    {
        putpixel(X+i,Y+29,z);
    }
// LINE 30
    for(i=16; i<25; i++)
    {
        putpixel(X+i,Y+30,z);
    }
    for(i=28; i<46; i++)
    {
        putpixel(X+i,Y+30,z);
    }
    for(i=52; i<75; i++)
    {
        putpixel(X+i,Y+30,z);
    }
    for(i=76; i<94; i++)
    {
        putpixel(X+i,Y+30,z);
    }
// LINE 31
    for(i=16; i<25; i++)
    {
        putpixel(X+i,Y+31,z);
    }
    for(i=28; i<32; i++)
    {
        putpixel(X+i,Y+31,z);
    }
    for(i=34; i<46; i++)
    {
        putpixel(X+i,Y+31,z);
    }
    for(i=52; i<95; i++)
    {
        putpixel(X+i,Y+31,z);
    }
// LINE 32
    for(i=15; i<26; i++)
    {
        putpixel(X+i,Y+32,z);
    }
    for(i=28; i<30; i++)
    {
        putpixel(X+i,Y+32,z);
    }
    for(i=32; i<47; i++)
    {
        putpixel(X+i,Y+32,z);
    }
    for(i=53; i<94; i++)
    {
        putpixel(X+i,Y+32,z);
    }
// LINE 33
    for(i=14; i<25; i++)
    {
        putpixel(X+i,Y+33,z);
    }
    for(i=30; i<46; i++)
    {
        putpixel(X+i,Y+33,z);
    }
    for(i=52; i<94; i++)
    {
        putpixel(X+i,Y+33,z);
    }
// LINE 34
    for(i=12; i<25; i++)
    {
        putpixel(X+i,Y+34,z);
    }
    for(i=29; i<39; i++)
    {
        putpixel(X+i,Y+34,z);
    }
    for(i=40; i<45; i++)
    {
        putpixel(X+i,Y+34,z);
    }
    for(i=52; i<94; i++)
    {
        putpixel(X+i,Y+34,z);
    }
// LINE 35
    for(i=10; i<25; i++)
    {
        putpixel(X+i,Y+35,z);
    }
    for(i=28; i<34; i++)
    {
        putpixel(X+i,Y+35,z);
    }
    for(i=35; i<38; i++)
    {
        putpixel(X+i,Y+35,z);
    }
    for(i=52; i<56; i++)
    {
        putpixel(X+i,Y+35,z);
    }
    for(i=61; i<95; i++)
    {
        putpixel(X+i,Y+35,z);
    }
// LINE 36
    for(i=7; i<25; i++)
    {
        putpixel(X+i,Y+36,z);
    }
    for(i=28; i<33; i++)
    {
        putpixel(X+i,Y+36,z);
    }
    for(i=51; i<56; i++)
    {
        putpixel(X+i,Y+36,z);
    }
    for(i=62; i<94; i++)
    {
        putpixel(X+i,Y+36,z);
    }
// LINE 37
    for(i=2; i<24; i++)
    {
        putpixel(X+i,Y+37,z);
    }
    for(i=51; i<57; i++)
    {
        putpixel(X+i,Y+37,z);
    }
    for(i=64; i<93; i++)
    {
        putpixel(X+i,Y+37,z);
    }
// LINE 38
    for(i=2; i<24; i++)
    {
        putpixel(X+i,Y+38,z);
    }
    for(i=51; i<56; i++)
    {
        putpixel(X+i,Y+38,z);
    }
    for(i=66; i<95; i++)
    {
        putpixel(X+i,Y+38,z);
    }
// LINE 39
    for(i=7; i<24; i++)
    {
        putpixel(X+i,Y+39,z);
    }
    for(i=52; i<55; i++)
    {
        putpixel(X+i,Y+39,z);
    }
    for(i=66; i<69; i++)
    {
        putpixel(X+i,Y+39,z);
    }
    for(i=71; i<92; i++)
    {
        putpixel(X+i,Y+39,z);
    }
    putpixel(X+94,Y+39,z);
// LINE 40
    for(i=8; i<24; i++)
    {
        putpixel(X+i,Y+40,z);
    }
    for(i=75; i<93; i++)
    {
        putpixel(X+i,Y+40,z);
    }
// LINE 41
    for(i=4; i<5; i++)
    {
        putpixel(X+i,Y+41,z);
    }
    for(i=8; i<24; i++)
    {
        putpixel(X+i,Y+41,z);
    }
    for(i=75; i<96; i++)
    {
        putpixel(X+i,Y+41,z);
    }
// LINE 42
    for(i=4; i<6; i++)
    {
        putpixel(X+i,Y+42,z);
    }
    for(i=8; i<24; i++)
    {
        putpixel(X+i,Y+42,z);
    }
    for(i=54; i<57; i++)
    {
        putpixel(X+i,Y+42,z);
    }
    for(i=74; i<97; i++)
    {
        putpixel(X+i,Y+42,z);
    }
// LINE 43
    for(i=5; i<24; i++)
    {
        putpixel(X+i,Y+43,z);
    }
    for(i=54; i<56; i++)
    {
        putpixel(X+i,Y+43,z);
    }
    for(i=72; i<98; i++)
    {
        putpixel(X+i,Y+43,z);
    }
// LINE 44
    for(i=6; i<24; i++)
    {
        putpixel(X+i,Y+44,z);
    }
    for(i=43; i<46; i++)
    {
        putpixel(X+i,Y+44,z);
    }
    for(i=51; i<55; i++)
    {
        putpixel(X+i,Y+44,z);
    }
    for(i=72; i<100; i++)
    {
        putpixel(X+i,Y+44,z);
    }
// LINE 45
    for(i=6; i<24; i++)
    {
        putpixel(X+i,Y+45,z);
    }
    for(i=42; i<57; i++)
    {
        putpixel(X+i,Y+45,z);
    }
    for(i=69; i<100; i++)
    {
        putpixel(X+i,Y+45,z);
    }
// LINE 46
    for(i=7; i<25; i++)
    {
        putpixel(X+i,Y+46,z);
    }
    for(i=42; i<59; i++)
    {
        putpixel(X+i,Y+46,z);
    }
    for(i=69; i<100; i++)
    {
        putpixel(X+i,Y+46,z);
    }
// LINE 47
    for(i=7; i<25; i++)
    {
        putpixel(X+i,Y+47,z);
    }
    for(i=42; i<45; i++)
    {
        putpixel(X+i,Y+47,z);
    }
    for(i=47; i<51; i++)
    {
        putpixel(X+i,Y+47,z);
    }
    for(i=52; i<59; i++)
    {
        putpixel(X+i,Y+47,z);
    }
    for(i=68; i<97; i++)
    {
        putpixel(X+i,Y+47,z);
    }
// LINE 48
    for(i=6; i<25; i++)
    {
        putpixel(X+i,Y+48,z);
    }
    for(i=42; i<44; i++)
    {
        putpixel(X+i,Y+48,z);
    }
    for(i=52; i<59; i++)
    {
        putpixel(X+i,Y+48,z);
    }
    for(i=68; i<98; i++)
    {
        putpixel(X+i,Y+48,z);
    }
// LINE 49
    for(i=6; i<25; i++)
    {
        putpixel(X+i,Y+49,z);
    }
    putpixel(X+45,Y+49,z);
    for(i=52; i<55; i++)
    {
        putpixel(X+i,Y+49,z);
    }
    for(i=65; i<97; i++)
    {
        putpixel(X+i,Y+49,z);
    }
// LINE 50
    for(i=7; i<26; i++)
    {
        putpixel(X+i,Y+50,z);
    }
    for(i=44; i<46; i++)
    {
        putpixel(X+i,Y+50,z);
    }
    for(i=51; i<55; i++)
    {
        putpixel(X+i,Y+50,z);
    }
    for(i=65; i<97; i++)
    {
        putpixel(X+i,Y+50,z);
    }
// LINE 51
    for(i=7; i<26; i++)
    {
        putpixel(X+i,Y+51,z);
    }
    for(i=44; i<47; i++)
    {
        putpixel(X+i,Y+51,z);
    }
    for(i=51; i<57; i++)
    {
        putpixel(X+i,Y+51,z);
    }
    for(i=65; i<97; i++)
    {
        putpixel(X+i,Y+51,z);
    }
// LINE 52
    for(i=7; i<27; i++)
    {
        putpixel(X+i,Y+52,z);
    }
    for(i=51; i<60; i++)
    {
        putpixel(X+i,Y+52,z);
    }
    for(i=65; i<97; i++)
    {
        putpixel(X+i,Y+52,z);
    }
// LINE 53
    for(i=7; i<26; i++)
    {
        putpixel(X+i,Y+53,z);
    }
    putpixel(X+40,Y+53,z);
    for(i=52; i<63; i++)
    {
        putpixel(X+i,Y+53,z);
    }
    for(i=67; i<97; i++)
    {
        putpixel(X+i,Y+53,z);
    }
// LINE 54
    for(i=6; i<29; i++)
    {
        putpixel(X+i,Y+54,z);
    }
    for(i=36; i<41; i++)
    {
        putpixel(X+i,Y+54,z);
    }
    putpixel(X+46,Y+54,z);
    for(i=49; i<64; i++)
    {
        putpixel(X+i,Y+54,z);
    }
    for(i=66; i<97; i++)
    {
        putpixel(X+i,Y+54,z);
    }
// LINE 55
    for(i=0; i<3; i++)
    {
        putpixel(X+i,Y+55,z);
    }
    for(i=5; i<26; i++)
    {
        putpixel(X+i,Y+55,z);
    }
    for(i=27; i<31; i++)
    {
        putpixel(X+i,Y+55,z);
    }
    for(i=35; i<41; i++)
    {
        putpixel(X+i,Y+55,z);
    }
    for(i=43; i<97; i++)
    {
        putpixel(X+i,Y+55,z);
    }
// LINE 56
    for(i=2; i<29; i++)
    {
        putpixel(X+i,Y+56,z);
    }
    for(i=35; i<38; i++)
    {
        putpixel(X+i,Y+56,z);
    }
    for(i=39; i<98; i++)
    {
        putpixel(X+i,Y+56,z);
    }
// LINE 57
    for(i=2; i<9; i++)
    {
        putpixel(X+i,Y+57,z);
    }
    for(i=11; i<28; i++)
    {
        putpixel(X+i,Y+57,z);
    }
    for(i=34; i<37; i++)
    {
        putpixel(X+i,Y+57,z);
    }
    for(i=39; i<44; i++)
    {
        putpixel(X+i,Y+57,z);
    }
    for(i=51; i<97; i++)
    {
        putpixel(X+i,Y+57,z);
    }
// LINE 58
    for(i=5; i<7; i++)
    {
        putpixel(X+i,Y+58,z);
    }
    for(i=12; i<29; i++)
    {
        putpixel(X+i,Y+58,z);
    }
    for(i=34; i<37; i++)
    {
        putpixel(X+i,Y+58,z);
    }
    for(i=39; i<42; i++)
    {
        putpixel(X+i,Y+58,z);
    }
    for(i=54; i<59; i++)
    {
        putpixel(X+i,Y+58,z);
    }
    for(i=60; i<97; i++)
    {
        putpixel(X+i,Y+58,z);
    }
// LINE 59
    for(i=5; i<7; i++)
    {
        putpixel(X+i,Y+59,z);
    }
    for(i=13; i<30; i++)
    {
        putpixel(X+i,Y+59,z);
    }
    for(i=34; i<37; i++)
    {
        putpixel(X+i,Y+59,z);
    }
    for(i=53; i<97; i++)
    {
        putpixel(X+i,Y+59,z);
    }
// LINE 60
    for(i=4; i<7; i++)
    {
        putpixel(X+i,Y+60,z);
    }
    for(i=14; i<31; i++)
    {
        putpixel(X+i,Y+60,z);
    }
    for(i=34; i<37; i++)
    {
        putpixel(X+i,Y+60,z);
    }
    for(i=43; i<47; i++)
    {
        putpixel(X+i,Y+60,z);
    }
    for(i=50; i<97; i++)
    {
        putpixel(X+i,Y+60,z);
    }
// LINE 61
    for(i=4; i<8; i++)
    {
        putpixel(X+i,Y+61,z);
    }
    for(i=13; i<31; i++)
    {
        putpixel(X+i,Y+61,z);
    }
    for(i=34; i<36; i++)
    {
        putpixel(X+i,Y+61,z);
    }
    for(i=43; i<96; i++)
    {
        putpixel(X+i,Y+61,z);
    }
// LINE 62
    for(i=4; i<9; i++)
    {
        putpixel(X+i,Y+62,z);
    }
    for(i=11; i<32; i++)
    {
        putpixel(X+i,Y+62,z);
    }
    for(i=43; i<95; i++)
    {
        putpixel(X+i,Y+62,z);
    }
// LINE 63
    for(i=5; i<32; i++)
    {
        putpixel(X+i,Y+63,z);
    }
    for(i=51; i<95; i++)
    {
        putpixel(X+i,Y+63,z);
    }
// LINE 64
    for(i=7; i<32; i++)
    {
        putpixel(X+i,Y+64,z);
    }
    putpixel(X+34,Y+64,z);
    for(i=55; i<94; i++)
    {
        putpixel(X+i,Y+64,z);
    }
// LINE 65
    putpixel(X+4,Y+65,z);
    for(i=8; i<31; i++)
    {
        putpixel(X+i,Y+65,z);
    }
    for(i=34; i<37; i++)
    {
        putpixel(X+i,Y+65,z);
    }
    for(i=58; i<94; i++)
    {
        putpixel(X+i,Y+65,z);
    }
// LINE 66
    for(i=4; i<6; i++)
    {
        putpixel(X+i,Y+66,z);
    }
    for(i=7; i<32; i++)
    {
        putpixel(X+i,Y+66,z);
    }
    for(i=34; i<37; i++)
    {
        putpixel(X+i,Y+66,z);
    }
    for(i=59; i<94; i++)
    {
        putpixel(X+i,Y+66,z);
    }
// LINE 67
    for(i=5; i<38; i++)
    {
        putpixel(X+i,Y+67,z);
    }
    for(i=57; i<93; i++)
    {
        putpixel(X+i,Y+67,z);
    }
// LINE 68
    for(i=6; i<40; i++)
    {
        putpixel(X+i,Y+68,z);
    }
    for(i=55; i<94; i++)
    {
        putpixel(X+i,Y+68,z);
    }
// LINE 69
    for(i=6; i<41; i++)
    {
        putpixel(X+i,Y+69,z);
    }
    for(i=50; i<52; i++)
    {
        putpixel(X+i,Y+69,z);
    }
    for(i=53; i<93; i++)
    {
        putpixel(X+i,Y+69,z);
    }
// LINE 70
    for(i=7; i<45; i++)
    {
	putpixel(X+i,Y+70,z);
    }
    for(i=50; i<94; i++)
    {
	putpixel(X+i,Y+70,z);
    }
// LINE 71
    for(i=2; i<5; i++)
    {
	putpixel(X+i,Y+71,z);
    }
    for(i=11; i<93; i++)
    {
	putpixel(X+i,Y+71,z);
    }
// LINE 72
    for(i=1; i<4; i++)
    {
	putpixel(X+i,Y+72,z);
    }
    for(i=11; i<92; i++)
    {
	putpixel(X+i,Y+72,z);
    }
// LINE 73
    for(i=10; i<91; i++)
    {
	putpixel(X+i,Y+73,z);
    }
// LINE 74
    for(i=10; i<15; i++)
    {
	putpixel(X+i,Y+74,z);
    }
    for(i=17; i<91; i++)
    {
	putpixel(X+i,Y+74,z);
    }
// LINE 75
    putpixel(X+11,Y+75,z);
    for(i=17; i<91; i++)
    {
	putpixel(X+i,Y+75,z);
    }
    settextstyle(1,0,4);
    setcolor(RED);
    char name[21]=" ERNESTO CHE GUVARA",name2[21];
    for(i=0;i<21;i++)
    {
    name2[i]=name[i];
    name2[i+1]='\0';
    outtextxy(100,Y+80,name2);
    delay(250);
    }
    getch();
}
